export const ACTION_MOUSE_UP = 'ACTION_MOUSE_UP'
export const ACTION_MOUSE_DOWN = 'ACTION_MOUSE_DOWN'
export const ACTION_DRAW = 'ACTION_DRAW'
export const ACTION_UPDATE_OLD_POSITIONS = 'ACTION_UPDATE_OLD_POSITIONS'
